query {
  meetups {
    name
    date
    address
    id
    photo
    meetupGroup {
      meetupID
      country
      city
    }
    sponsors {
      role
      company {
        name
      }
    }
  }
}

