query speaker($id: String!) {
  speaker(id: $id){
    id
    name
    title
    email
    countries
    github
    speakersBureau
    company {
      id
      name
      websiteURL
    }
    presentations {
      id
      title
      duration
      meetup {
        name
        date
        id
      }
    }
  }
}
