query speakers {
    speakers {
      id
      name
      title
      email
      countries {
        name
      }
      github
      speakersBureau
      company {
        id
        name
      }
    }
}
